version: "3"
services:

  predict-drug-target-api:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./MolecularTransformerEmbeddings:/app/MolecularTransformerEmbeddings
    environment:
      - VIRTUAL_HOST=predict-drug-target.137.120.31.160.nip.io
      - LETSENCRYPT_HOST=predict-drug-target.137.120.31.160.nip.io
      # GPU: predict-drug-target.137.120.31.160.nip.io
      # CPU node3: predict-drug-target.137.120.31.148.nip.io
      - VIRTUAL_PORT=8000
    # ports:
    #   - 8000:8000
    # command: uvicorn --host 0.0.0.0 src.api:app --reload
