name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/actions/test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install .[test]

    - name: Prepare data and train the model
      run: |
        ./prepare.sh
        python src/train.py

    - name: Run tests
      run: |
        pytest -s
